// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_sessions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAuthSession = `-- name: CreateAuthSession :one
INSERT INTO
  auth_sessions (id, user_id, refresh_token_hash, expires_at)
VALUES
  (
    $1,
    $2,
    $3,
    $4
  ) RETURNING id,
  user_id,
  expires_at,
  created_at
`

type CreateAuthSessionParams struct {
	SessionID        uuid.UUID          `json:"session_id"`
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

type CreateAuthSessionRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (CreateAuthSessionRow, error) {
	row := q.db.QueryRow(ctx, createAuthSession,
		arg.SessionID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
	)
	var i CreateAuthSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveAuthSession = `-- name: GetActiveAuthSession :one
SELECT
  id,
  user_id,
  refresh_token_hash,
  expires_at
FROM
  auth_sessions
WHERE
  id = $1
  AND revoked_at IS NULL
  AND expires_at > now ()
`

type GetActiveAuthSessionRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetActiveAuthSession(ctx context.Context, sessionID uuid.UUID) (GetActiveAuthSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveAuthSession, sessionID)
	var i GetActiveAuthSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
	)
	return i, err
}

const revokeAuthSession = `-- name: RevokeAuthSession :exec
UPDATE auth_sessions
SET
  revoked_at = now ()
WHERE
  id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAuthSession(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAuthSession, sessionID)
	return err
}

const rotateAuthSession = `-- name: RotateAuthSession :one
UPDATE auth_sessions
SET
  refresh_token_hash = $1,
  last_used_at = now ()
WHERE
  id = $2
  AND refresh_token_hash = $3
  AND revoked_at IS NULL
  AND expires_at > now () RETURNING id,
  user_id,
  expires_at
`

type RotateAuthSessionParams struct {
	NewRefreshTokenHash     string    `json:"new_refresh_token_hash"`
	SessionID               uuid.UUID `json:"session_id"`
	CurrentRefreshTokenHash string    `json:"current_refresh_token_hash"`
}

type RotateAuthSessionRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) RotateAuthSession(ctx context.Context, arg RotateAuthSessionParams) (RotateAuthSessionRow, error) {
	row := q.db.QueryRow(ctx, rotateAuthSession, arg.NewRefreshTokenHash, arg.SessionID, arg.CurrentRefreshTokenHash)
	var i RotateAuthSessionRow
	err := row.Scan(&i.ID, &i.UserID, &i.ExpiresAt)
	return i, err
}
